INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Spring reference v1.0', 'Pivotal', 'Spring ref for developers', '2004');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Spring reference v2.0', 'Pivotal', 'Spring ref for developers', '2008');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Spring reference v3.1', 'Pivotal', 'Spring ref for developers', '2012');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Spring reference v4.0.3', 'Pivotal', 'Spring ref for developers', '2014');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Spring reference v4.3.7', 'Pivotal', 'Spring ref for developers', '2016');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Maven tutorial 1 edition', 'Apache', 'Official maven doc', '2007');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Maven tutorial 2 edition', 'Apache', 'Official maven doc', '2011');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Maven tutorial 3 edition', 'Apache', 'Official maven doc', '2013');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Maven tutorial 4 edition', 'Apache', 'Official maven doc', '2015');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 1.0 doc api', 'Sun MicroSystems', 'Java - official documentation', '1994');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 1.1 doc api', 'Sun MicroSystems', 'Java - official documentation', '1995');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 1.2 doc api', 'Sun MicroSystems', 'Java - official documentation', '1997');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 1.3 doc api', 'Sun MicroSystems', 'Java - official documentation', '1999');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 1.4 doc api', 'Sun MicroSystems', 'Java - official documentation', '2002');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 5.0 doc api', 'Sun MicroSystems', 'Java - official documentation', '2004');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 6 doc api', 'Oracle inc.', 'Java - official documentation', '2008');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 7 doc api', 'Oracle inc.', 'Java - official documentation', '2011');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 8 doc api', 'Oracle inc.', 'Java - official documentation', '2014');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Java 9 doc api', 'Oracle inc.', 'Java - official documentation', '2017');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Cassandra db reference v1', 'Apache', 'Cassandra db reference for developers', '2010');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Cassandra db reference v2', 'Apache', 'Cassandra db reference for developers', '2013');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Cassandra db reference v3', 'Apache', 'Cassandra db reference for developers', '2015');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Guava core library doc 1 edition', 'Google inc.', 'Guava core library official documentation', '2011');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Guava core library doc 2 edition', 'Google inc.', 'Guava core library official documentation', '2013');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Guava core library doc 3 edition', 'Google inc.', 'Guava core library official documentation', '2014');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Guava core library doc 4 edition', 'Google inc.', 'Guava core library official documentation', '2016');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Hibernate 1.0 tutorial', 'JBoss', 'Hibernate 1.0 tutorial', '2008');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Hibernate 2.0 tutorial', 'JBoss', 'Hibernate 2.0 tutorial', '2013');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Hibernate 3.0 tutorial', 'JBoss', 'Hibernate 3.0 tutorial', '2015');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('MySQL tutorial version 4.0', 'Oracle inc.', 'Final giude for popular databases', '1997');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('MySQL tutorial version 4.1', 'Oracle inc.', 'Final giude for popular databases', '1999');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('MySQL tutorial version 5.0', 'Oracle inc.', 'Final giude for popular databases', '2001');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('MySQL tutorial version 5.5', 'Oracle inc.', 'Final giude for popular databases', '2007');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('MySQL tutorial version 6.0', 'Oracle inc.', 'Final giude for popular databases', '2012');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('MySQL tutorial version 5.6', 'Oracle inc.', 'Final giude for popular databases', '2015');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('MySQL tutorial version 5.7', 'Oracle inc.', 'Final giude for popular databases', '2016');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Oracle database tutorial version 7', 'Oracle inc.', 'Overview of oracle db', '1997');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Oracle database tutorial version 8', 'Oracle inc.', 'Overview of oracle db', '1999');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Oracle database tutorial version 9', 'Oracle inc.', 'Overview of oracle db', '2001');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Oracle database tutorial version 10', 'Oracle inc.', 'Overview of oracle db', '2005');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Oracle database tutorial version 11', 'Oracle inc.', 'Overview of oracle db', '2010');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Oracle database tutorial version 12', 'Oracle inc.', 'Overview of oracle db', '2013');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('.NET tutorial 1 edition', 'Ernst Young', 'Popular technology description in one book', '2005');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('.NET tutorial 2 edition', 'Ernst Young', 'Popular technology description in one book', '2008');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('.NET tutorial 3 edition', 'Ernst Young', 'Popular technology description in one book', '2012');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('.NET tutorial 4 edition', 'Ernst Young', 'Popular technology description in one book', '2014');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('.NET tutorial 5 edition', 'Ernst Young', 'Popular technology description in one book', '2016');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Apache tomcat 6 tutorial', 'Apache inc.', 'The best Web Server for Java tutorial', '2010');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Apache tomcat 7 tutorial', 'Apache inc.', 'The best Web Server for Java tutorial', '2012');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Apache tomcat 8 tutorial', 'Apache inc.', 'The best Web Server for Java tutorial', '2014');
INSERT INTO `epam_library`.`book` (`title`, `author`, `brief`, `publish_year`) VALUES ('Apache tomcat 9 tutorial', 'Apache inc.', 'The best Web Server for Java tutorial', '2016');

INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('John Smith', 'matrix@gmail.com', '1985-05-13');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Carry Browich', 'brom@gmail.com', '1987-09-23');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Adam Cassndra', 'casd@gmail.com', '1995-08-17');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Anton Dobkin', 'askark@gmail.com', '1985-12-08');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Andrew Newmann', 'newman@gmail.com', '1988-02-18');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Bob Marley', 'marycallme@gmail.com', '1985-12-10');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Joe Robinson', 'robrobrob@gmail.com', '1982-12-08');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Antony Richardson', 'ratata@gmail.com', '1987-05-05');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Sarah Lowson', 'haramam@gmail.com', '1991-05-23');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Mary Smart', 'iamjustsmart@gmail.com', '1985-05-13');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Johanna Smath', 'vikingcuriosity@gmail.com', '1989-02-17');
INSERT INTO `epam_library`.`employee` (`name`, `email`, `date_of_birth`) VALUES ('Kirsten Dust', 'ddhasfho@gmail.com', '1975-11-03');
